//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EID { get; set; }
        public string EmpName { get; set; }
        public string EmpGender { get; set; }
        public string EmpAddr { get; set; }
        public Nullable<int> EmpSalary { get; set; }
        public Nullable<int> DeptID { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
